programme_tsv=[
  ["Date", "Time", "Session", "Speaker", "Affiliation / Role", "Location", "Talk Title"],
  ["April 24", "9:00 – 9:25", "Registration", "—", "—", "—", "—"],
  ["April 24", "9:25 – 9:40", "Opening Ceremony", "—", "—", "—", "—"],
  ["April 24", "9:40 – 10:10", "Opening Lecture", "Qiang Hu", "Chair Professor and Head, Department of Engineering Biology, Faculty of Synthetic Biology, Shenzhen University of Advanced Technology (SUAT)", "Shenzhen, China", "Marine Algae as a Sustainable Driver of Blue Biomanufacturing"],
  ["April 24", "10:10 – 10:30", "Session 1", "Miguel Pombo", "Founder of Azores Life Science/Ignae", "Portugal", "Powerful actives from the natural marine and aquatic resources of the Azores"],
  ["April 24", "10:30 – 10:50", "Session 1", "Pedro Lima", "CEO and co-founder of Sea4Us", "Portugal", "Marine inspired molecules for therapies of neurological unmet clinical needs"],
  ["April 24", "10:50 – 11:10", "Session 1", "James Chang", "Managing Director, Geb Impact Technology", "Hong Kong, China", "How Microalgae Revolutionize the Future of Protein"],
  ["April 24", "11:10 – 11:40", "Coffee Break & Networking", "—", "—", "Room USJ102, 1/F Academic Building", "—"],
  ["April 24", "11:40 – 12:00", "Session 2", "Speaker TBC", "—", "—", "Title TBC"],
  ["April 24", "12:00 – 12:20", "Session 2", "Yu Rencheng", "Professor, Institute of Oceanology, Chinese Academy of Sciences", "Qingdao, China", "Monitoring harmful algal blooms to protect seafood safety"],
  ["April 24", "12:20 – 12:40", "Session 2", "Manuela Pintado", "Universidade Católica Portuguesa and Blue Biotech", "—", "—"],
  ["April 24", "12:40 – 13:00", "Session 2", "Wen-Jun Li", "Distinguished Professor, School of Life Sciences, Sun Yat-Sen University", "Guangzhou, China", "Frontier Exploration and Application Expansion of Marine Microbial Resources"],
  ["April 24", "13:00 – 14:30", "Lunch", "—", "—", "18/F Residential Hall", "For Speakers only"],
  ["April 24", "14:30 – 14:50", "Session 3", "Wei Yu", "CEO & Founder, Xiaozao Tech", "Shenzhen, China", "Why Nannochloropis can be NEXT Gen of synbio chassis for bioactives?"],
  ["April 24", "14:50 – 15:10", "Session 3", "Helena Abreu", "President of the International Seaweed Association", "Portugal", "From Research to Industry: Portugal’s Algae Innovation Landscape"],
  ["April 24", "15:10 – 15:30", "Session 3", "Jorge Dias", "CEO of SPAROS LDA", "Portugal", "Nutrition Optimization: Towards a sustainable aquaculture production of fish and shrimp"],
  ["April 24", "15:30 – 15:50", "Session 3", "Shi Yanxi", "Founder of Zhuhai Biori Biotechnology Co., Ltd.", "Zhuhai, China", "Innovative Development of Raw Materials for Molecular Diagnostic Reagents"],
  ["April 24", "15:50 – 16:10", "Session 3", "Speaker TBC", "—", "—", "Title TBC"],
  ["April 24", "16:10 – 16:40", "Coffee Break & Networking", "—", "—", "Room USJ102, 1/F Academic Building", "—"],
  ["April 24", "16:40 – 17:00", "Session 4", "Pedro Rodrigues", "Associate Director of Faculty of Biotechnology, Universidade Católica Portuguesa", "Porto, Portugal", "Sustainable and Health-focused AI-based Decision Support Systems in Biotechnology and Biomedicine"],
  ["April 24", "17:00 – 17:20", "Session 4", "Wang Yong", "Professor, Tsinghua Shenzhen International Graduate School / Shenzhen Blue Ocean Deep Sea Equipment Technology co., ltd", "Shenzhen, China", "In situ sampling from the deep ocean for high-value natural products"],
  ["April 24", "17:20 – 17:40", "Session 4", "Simon Lee", "Chair Professor of Biomedical Sciences, The Hong Kong Polytechnic University", "Hong Kong, China", "Cnidarian peptide: a new source of various ion channel modulators and hormone signaling molecules against central nervous systems disease"],
  ["April 24", "17:40 – 18:00", "Session 4", "Pedro Pousão", "Researcher, President of the Scientific Council, Head of Estação Piloto de Piscicultura de Olhão (EPPO), Instituto Português do Mar e da Atmosfera", "Portugal", "Meeting the challenges in seafood research: aquaculture and bioprospection"],
  ["April 24", "Evening", "Gala Dinner", "—", "—", "Marmeleira Seafood Restaurant", "For Speakers only"],
  ["April 25", "9:00 – 9:20", "Session 5", "Angela Kam", "Macau International Carbon Emission Exchange", "Macau, China", "Title TBC"],
  ["April 25", "9:20 – 9:40", "Session 5", "Chan Yi Ngok", "Director, Pudong-Hong Kong Institute for Technology Transfer and Innovation; Executive Vice Chairman, Guangdong-Hong Kong-Macao Greater Bay Area Biotechnology Alliance", "Hong Kong, China", "On transfer of sustainable technology: the Hong Kong-Pudong experience"],
  ["April 25", "9:40 – 10:00", "Session 5", "Benedita Chaves", "Innovation Director of LIPOR", "Portugal", "From trash to treasure – an innovation strategy"],
  ["April 25", "10:00 – 10:20", "Session 5", "André Antunes", "Associate Professor, University of Saint Joseph", "Macau, China", "Bridging the gap between geo- and biosciences: Biotechnological applications of biominerals"],
  ["April 25", "10:20 – 10:50", "Coffee Break & Networking", "—", "—", "Room USJ102, 1/F Academic Building", "—"],
  ["April 25", "10:50 – 11:10", "Session 6", "Manuela Pintado", "Director of the Centre for Biotechnology and Fine Chemistry, Universidade Católica Portuguesa", "Porto, Portugal", "Creating Value from Agrifood losses and waste"],
  ["April 25", "11:10 – 11:30", "Session 6", "Luís Rochartre Álvares", "Senior Advisor of Planetiers New Generation", "Portugal", "From Sustainability to Regeneration: What Changes?"],
  ["April 25", "11:30 – 11:50", "Session 6", "Deepa Alex Mora", "Founder and Managing Director of BioMyne – Biotech Innovation and Engineering Limited", "Macau, China", "Macau-Hengqin: Bridging Sustainable Biotech Innovation Across Borders"],
  ["April 25", "11:50 – 12:10", "Session 6", "Débora Campos", "Founder and CEO of AgroGrIN Tech", "Portugal", "Boosting Pineapple Side-Streams to Zero: Steps towards Scale-Up (Pep4Fish Project)"],
  ["April 25", "12:10 – 12:30", "Session 6", "Isabel Braga da Cruz", "Pro-Rector for Sustainability, Universidade Católica Portuguesa", "Porto, Portugal", "Sustainability in Action: The Case of Universidade Católica Portuguesa - Towards Social and Economic Impact"],
  ["April 25", "12:30 – 12:40", "Closing Remarks", "—", "—", "—", "—"],
  ["April 25", "12:40 – 14:30", "Lunch", "—", "—", "Tromba Rija", "For Speakers only"],
  ["April 25", "15:00 – 17:00", "Sustainability Tour", "—", "—", "The Venetian Macao", "Visit to SANDS China sustainability facilities (for Speakers only)"]
]
